# How-to-handle-Imbalanced-Data-in-Python

The dataset is very big, (150MB) hence unable to upload in the repository
